### ISSUE TITLE
Seems like you have a idea similar to web components.

### ISSUE THREAD

**Issue by derek-dchu** [wmantly/jq-repeat#1]
Checkout following links:
http://css-tricks.com/modular-future-web-components/
[Polymer project](https://www.polymer-project.org/)

**Comment by derek-dchu** [comment]
Update title.

**Comment by wmantly** [comment]
I got the idea from working with AngularJS a while back, i loved ng-repeat but did not care for how over bearing Angular is. 
I am looking for help with this project, mostly in cleaning up and extending the documentation, care to join?

**Comment by derek-dchu** [comment]
Ok, I get the idea now. What will be the dependency for this one? We can still make it as a web component and design a style for it if you want.

**Comment by derek-dchu** [comment]
Seems like you already finished it? I can help you generate gulp configuration for testing and deployment (minify etc.).

**Comment by wmantly** [comment]
I wrote that over the summer, I want to re-factor it to make it more OO.

**Comment by derek-dchu** [comment]
I see. It looks pretty cool. We can also make it available on bower.

**Comment by derek-dchu** [comment]
Now, it is available on bower.
